/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <onboard_leds.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define HSI_CLOCK			16000000U
#define SYSTICK_TIM_CLK 	HSI_CLOCK

void Init_Systick_Timer(uint32_t tick_hz);

uint32_t volatile system_tick = 0;
uint32_t volatile timer_1 = 0;

int main(void)
{
	Init_Onboard_LEDs();
	Init_Systick_Timer(1000);		// 1000 Hz
	/* Loop forever */
	for (;;)
	{
		if (system_tick - timer_1 >= 1000)
		{
			All_LEDs_Toggle();
			timer_1 = system_tick;
		}
	}
}

void Init_Systick_Timer(uint32_t tick_hz)
{
// SysTick Reload Value Register
	uint32_t volatile *const pSRVR = (uint32_t*) 0xE000E014;

// SysTick Control and Status Register
	uint32_t volatile *const pSCSR = (uint32_t*) 0xE000E010;

	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz) - 1;

// Clear the value of pSRVR
	*pSRVR &= ~(0x00FFFFFF);

// Load the reload value into pSRVR
	*pSRVR |= count_value;

// Do some configuration
	*pSCSR |= (1 << 1);
	*pSCSR |= (1 << 2);

// Enable the systick
	*pSCSR |= (1 << 0);
}

void SysTick_Handler()
{
	system_tick++;
}
