/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define BIT_BAND_BASE 0x20000000
#define ALIAS_BASE_ADDR 0x22000000
#define BIT_BAND_MEMORY_ADDR 0x20000200

int main(void)
{
	/**
	 *
	 * Calculate the bit band alias address for given bit band memory address
	 * and bit position 7th bit position of the memory location 0x2000_0200 using
	 * its alias address.
	 *
	 *
	 * General formula:
	 * alias_address = alias_base + ((bit_band_memory_address - bit_band_base) * 32) + bit * 4
	 *
	 *
	 * Solution:
	 * Example: for SRAM
	 * alias_base = 0x2200_0000
	 * bit_band_memory_address = 0x2000_0200 (given address)
	 * bit_band_base = 0x2000_0000
	 * bit = 7 (7th bit)
	 *
	 *
	 */

	uint8_t *ptr = (uint8_t*) 0x20000200;

	// initialize value
	*ptr = 0xff;

	// normal method
	// clearing 7th bit position
	*ptr &= ~(1 << 7);

	// initialize value
	*ptr = 0xff;

	// bit band method
	uint8_t* alias_address = (uint8_t*) (ALIAS_BASE_ADDR + ((BIT_BAND_MEMORY_ADDR - BIT_BAND_BASE) * 32) + 7 * 4);

	*alias_address = 0;


	/* Loop forever */
	for (;;)
		;
}
