/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef struct
{
	uint32_t gpio_a_en	:1;
	uint32_t gpio_b_en	:1;
	uint32_t gpio_c_en	:1;
	uint32_t gpio_d_en	:1;
	uint32_t gpio_e_en	:1;
	uint32_t reserve_1	:2;
	uint32_t gpio_h_en	:1;
	uint32_t reserve_2	:4;
	uint32_t crc_en		:1;
	uint32_t reserve_3	:8;
	uint32_t dma_1_en	:1;
	uint32_t dma_2_en	:1;
	uint32_t reserve_4	:9;
} RCC_AHB1_ENR_t ;


int main(void)
{
    /* Loop forever */
	for(;;);
}
