/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * Write a program to add, subtract, multiply and divide 2 operands
 * using SVC handler and return the result to the thread mode code
 * and print the result. Thread mode code should pass 2 operands via
 * the stack frame.
 *
 * Service number
 * 36: addition
 * 37: subtraction
 * 38: multiplication
 * 39: division
 *
 */

#include <stdio.h>
#include <stdint.h>
#include "math.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	float value_1 = 1;
	float value_2 = 2;
	float result;

	printf("Operand 1: %f\n", value_1);
	printf("Operand 2: %f\n", value_2);
	printf("\n");
	printf("Addition: %f\n", add(value_1, value_2));
	printf("Subtraction: %f\n", subtract(value_1, value_2));
	printf("Multiplication: %f\n", multiply(value_1, value_2));
	printf("Division: %f\n", divide(value_1, value_2));

	/* Loop forever */
	for (;;)
		;
}
