/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Stack memory calculation
#define SIZE_TASK_STACK			(1024U)
#define	SIZE_SCHED_STACK 		(1024U)

#define SRAM_START				(0x20000000U)
#define SIZE_RAM				((128) * (1024))
#define SRAM_END				((SRAM_START) + (SIZE_RAM))

#define T1_STACK_START			SRAM_END
#define T2_STACK_START			((SRAM_END) - (SIZE_TASK_STACK) * (1))
#define T3_STACK_START			((SRAM_END) - (SIZE_TASK_STACK) * (2))
#define T4_STACK_START			((SRAM_END) - (SIZE_TASK_STACK) * (3))
#define SCHED_STACK_START		((SRAM_END) - (SIZE_TASK_STACK) * (4))

void task1_handler();
void task2_handler();
void task3_handler();
void task4_handler();

int main(void)
{
	/* Loop forever */
	for (;;)
		;
}

void task1_handler()
{
	while (1)
	{
		printf("This is task 1\n");
	}
}

void task2_handler()
{
	while (1)
	{
		printf("This is task 2\n");
	}
}

void task3_handler()
{
	while (1)
	{
		printf("This is task 3\n");
	}
}

void task4_handler()
{
	while (1)
	{
		printf("This is task 4\n");
	}
}
