/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Stack memory calculation
#define SIZE_TASK_STACK			(1024U)
#define	SIZE_SCHED_STACK 		(1024U)

#define SRAM_START				(0x20000000U)
#define SIZE_RAM				((128) * (1024))
#define SRAM_END				((SRAM_START) + (SIZE_RAM))

#define T1_STACK_START			SRAM_END
#define T2_STACK_START			((SRAM_END) - (SIZE_TASK_STACK) * (1))
#define T3_STACK_START			((SRAM_END) - (SIZE_TASK_STACK) * (2))
#define T4_STACK_START			((SRAM_END) - (SIZE_TASK_STACK) * (3))
#define SCHED_STACK_START		((SRAM_END) - (SIZE_TASK_STACK) * (4))

#define TICK_HZ 			1000U

#define HSI_CLOCK			16000000U
#define SYSTICK_TIM_CLK 	HSI_CLOCK

void initSystickTimer(uint32_t tick_hz);

void task1_handler();
void task2_handler();
void task3_handler();
void task4_handler();

uint32_t volatile timer = 0;

int main(void)
{
	printf("Hello\n");
	initSystickTimer(TICK_HZ);
	/* Loop forever */
	for (;;)
		;
}

void task1_handler()
{
	while (1)
	{
		printf("This is task 1\n");
	}
}

void task2_handler()
{
	while (1)
	{
		printf("This is task 2\n");
	}
}

void task3_handler()
{
	while (1)
	{
		printf("This is task 3\n");
	}
}

void task4_handler()
{
	while (1)
	{
		printf("This is task 4\n");
	}
}

void initSystickTimer(uint32_t tick_hz)
{
	// SysTick Reload Value Register
	uint32_t volatile *const pSRVR = (uint32_t*) 0xE000E014;

	// SysTick Control and Status Register
	uint32_t volatile *const pSCSR = (uint32_t*) 0xE000E010;

	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz) - 1;

	// Clear the value of pSRVR
	*pSRVR &= ~(0x00FFFFFF);

	// Load the reload value into pSRVR
	*pSRVR |= count_value;

	// Do some configuration
	*pSCSR |= (1 << 1);
	*pSCSR |= (1 << 2);

	// Enable the systick
	*pSCSR |= (1 << 0);
}

void SysTick_Handler()
{
	timer++;
	if (timer % 1000)
	{
		printf("%u\n", timer);
	}
}
