/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	__asm volatile ("LDR R1,=#0x20001000");		// load address 0x20001000 to register R1
	__asm volatile ("LDR R2,=#0x20001004");		// load address 0x20001004 to register R2
	__asm volatile ("LDR R0,[R1]");				// load value from address in register R1 to register R0
	__asm volatile ("LDR R1,[R2]");				// load value from address in register R2 to register R1
	__asm volatile ("ADD R0,R0,R1");			// Calculate sum value of register R0 and R1, then store in register R0
	__asm volatile ("STR R0,[R2]");				// Store result back to register that has address in R2 0x20001004
    /* Loop forever */
	for(;;);
}
