/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 * Write a program to execute an SVC instruction from thread mode,
 * implement the SVC handler to print the SVC number used.
 * Also, increment the SVC number by 4 and return it to thread mode code and print it.
 *
 * Hints:
 * 1. Write a main() where you should execute the SVC instruction with an argument.
 * Let's say SVC #0x5
 * 2. Implement the SVC handler.
 * 3. In the SVC handler, extract the SVC number and print it using printf.
 * 4. Increment the SVC number by 4 and return it to the thread mode.
 *
 */

int main(void)
{
	__asm volatile ("SVC #0x05");

	uint32_t data;

	__asm volatile ("MOV %0,r0": "=r"(data)::);
	printf("Data: %u\n", data);

	/* Loop forever */
	for (;;);
}

/**
 * IMPORTANT: to extract the argument of SVC in handler function,
 * we have to write it in __attribute__ ((naked)) as follow
 * "__attribute__ ((naked)) void SVC_Handler(void)"
 * since "In assembly language programming, the function prologue
 * is a few lines of ASM code at the beginning of a function,
 * which prepare the stack! and registers for use within the function".
 * Therefore, we will lose the value of SVC argument.
 *
 * With __attribute__ ((naked)), there is no prologue, so we can get the exact
 * value of MSP in stack, then we can extract the value of SVC argument!
 *
 */

__attribute__ ((naked)) void SVC_Handler(void)
{
	// 1. Get the value of MSP
	__asm volatile ("MRS R0,MSP");
	__asm volatile ("B SVC_Handler_C");
}

void SVC_Handler_C(uint32_t volatile *const p_base_of_stack_frame)
{
	printf("In SVC handler\n");
	// 2. Increment the pointer to the base of the stack frame by 6 to get the return address
	// of the program counter (check slide "How to extract the SVC number")
	uint8_t volatile *p_return_addr = (uint8_t*) p_base_of_stack_frame[6];

	// 3. Decrement the return address by 2 to point to
	// opcode of the SVC instruction in the program memory (check Show view Disassembly)
	p_return_addr -= 2;

	// 4. Extract the SVC number
	uint8_t const svc_number = *p_return_addr;
	printf("Number is %u\n", svc_number);
	uint8_t new_value_svc_number = svc_number + 4;
	p_base_of_stack_frame[0] = new_value_svc_number;
}
