/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Turn on green LED - PD12

	uint32_t *p_clock_control_reg = (uint32_t*) 0x40023830;
	uint32_t *p_port_d_mode_reg = (uint32_t*) 0x40020C00;
	uint32_t *p_port_d_output_reg = (uint32_t*) 0x40020C14;

	// 1. Enable the clock for GPIOD peripheral in the AHB1ENR
	*p_clock_control_reg |= (1 << 3);

	// 2. Configure the mode of the IO pin as output
	// a. Clear the 24th and 25th bit position (CLEAR)
	*p_port_d_mode_reg &= ~(3 << 24);
	// b. Make 24th bit as 1 (SET)
	*p_port_d_mode_reg |= (1 << 24);

	//3. Set 12th bit of the output data register to make I/O pin-12 as HIGH
	*p_port_d_output_reg |= (1 << 12);

    /* Loop forever */
	for(;;);
}
