/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Used pins
 *
 * PC1 - C4 (input)
 * PC3 - C3 (input)
 * PA1 - C2 (input)
 * PA3 - C1 (input)
 * PA5 - R4 (output)
 * PA7 - R3 (output)
 * PC5 - R2 (output)
 * PB1 - R1 (output)
 *
 */

int main(void)
{
	/* Reset and clock control reg */
	RCC_AHB1_ENR_t
	volatile *const p_clock_control_reg = (RCC_AHB1_ENR_t*) RCC;

	/* GPIO A Configuration */
	p_clock_control_reg->gpio_a_en = 1;
	GPIOx_MODE_REG_t volatile *const p_port_a_mode_reg =
			(GPIOx_MODE_REG_t*) GPIO_A;
	GPIOx_PUPDR_t volatile *const p_port_a_pull_reg = (GPIOx_PUPDR_t*) GPIO_A;
	GPIOx_IDR_t volatile const *const p_port_a_input_reg = (GPIOx_IDR_t*) GPIO_A;
	GPIOx_ODR_t volatile *const p_port_a_output_reg = (GPIOx_ODR_t*) GPIO_A;

	/* GPIO B Configuration */
	p_clock_control_reg->gpio_b_en = 1;
	GPIOx_MODE_REG_t volatile *const p_port_b_mode_reg =
			(GPIOx_MODE_REG_t*) GPIO_B;
	GPIOx_PUPDR_t volatile *const p_port_b_pull_reg = (GPIOx_PUPDR_t*) GPIO_B;
	GPIOx_IDR_t volatile const *const p_port_b_input_reg = (GPIOx_IDR_t*) GPIO_B;
	GPIOx_ODR_t volatile *const p_port_b_output_reg = (GPIOx_ODR_t*) GPIO_B;

	/* GPIO C Configuration */
	p_clock_control_reg->gpio_c_en = 1;
	GPIOx_MODE_REG_t volatile *const p_port_c_mode_reg =
			(GPIOx_MODE_REG_t*) GPIO_C;
	GPIOx_PUPDR_t volatile *const p_port_c_pull_reg = (GPIOx_PUPDR_t*) GPIO_C;
	GPIOx_IDR_t volatile const *const p_port_c_input_reg = (GPIOx_IDR_t*) GPIO_C;
	GPIOx_ODR_t volatile *const p_port_c_output_reg = (GPIOx_ODR_t*) GPIO_C;

	/* Input pins */
	/* PC1 - C4 (input) */
	p_port_c_mode_reg->pin_1 = INPUT_MODE;
	p_port_c_pull_reg->pin_1 = PULL_UP;

	/* PC3 - C3 (input) */
	p_port_c_mode_reg->pin_3 = INPUT_MODE;
	p_port_c_pull_reg->pin_3 = PULL_UP;

	/* PA1 - C2 (input) */
	p_port_a_mode_reg->pin_1 = INPUT_MODE;
	p_port_a_pull_reg->pin_1 = PULL_UP;

	/* PA3 - C1 (input) */
	p_port_a_mode_reg->pin_3 = INPUT_MODE;
	p_port_a_pull_reg->pin_3 = PULL_UP;

	/* Output pins */
	/* PA5 - R4 (output) */
	p_port_a_mode_reg->pin_5 = OUTPUT_MODE;

	/* PA7 - R3 (output) */
	p_port_a_mode_reg->pin_7 = OUTPUT_MODE;

	/* PC5 - R2 (output) */
	p_port_c_mode_reg->pin_5 = OUTPUT_MODE;

	/* PB1 - R1 (output) */
	p_port_b_mode_reg->pin_1 = OUTPUT_MODE;

	uint8_t row_output_address[4] =
	{ p_port_b_output_reg->pin_1, p_port_c_output_reg->pin_5,
			p_port_a_output_reg->pin_7, p_port_a_output_reg->pin_5 };

	uint8_t col_input_address[4] =
	{ p_port_a_input_reg->pin_3, p_port_a_input_reg->pin_1,
			p_port_c_input_reg->pin_3, p_port_c_input_reg->pin_1 };

	printf("Hello world!\n");
	/* Loop forever */
	while (1)
	{

	}
}
