/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f411xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void)
{
	for (int i = 0; i < 300000; i++)
		;
}

/*
 * SPI2 pins
 * NSS		PB12		AF05
 * SCLK		PB13		AF05
 * MISO		PB14		AF05
 * MOSI		PB15		AF05
 */

void SPI2_GPIOInits(void)
{
	GPIO_Handler_t SPIpins;
	SPIpins.pGPIOx = GPIOB;
	SPIpins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALT_FUNC;
	SPIpins.GPIO_PinConfig.GPIO_PinAltFuncMode = 5;
	SPIpins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	SPIpins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PULL;
	SPIpins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

	// SCLK
	SPIpins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_Init(&SPIpins);

	// MOSI
	SPIpins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	GPIO_Init(&SPIpins);

//	// MISO
//	SPIpins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
//	GPIO_Init(&SPIpins);
//
	// NSS
	SPIpins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIO_Init(&SPIpins);
}

void GPIO_ButtonInit()
{
	GPIO_Handler_t GPIO_button_h =
	{ 0 };
	GPIO_button_h.pGPIOx = GPIOA;
	GPIO_button_h.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	GPIO_button_h.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_INPUT;
	GPIO_button_h.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_button_h.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PULL;

	GPIO_Init(&GPIO_button_h);

	// IRQ Configuration
	GPIO_IRQ_Priority_Config(IRQ_EXTI0, NVIC_IRQ_PRIO15);
	GPIO_IRQ_IT_Config(IRQ_EXTI0, ENABLE);
}

void SPI2_Init()
{
	SPI_Handler_t SPI_send_tx_h;
	SPI_send_tx_h.pSPIx = SPI2;
	SPI_send_tx_h.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SPI_send_tx_h.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FULL_DUPLEX;
	SPI_send_tx_h.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV64; /* Generate sclk of 2 MHz */
	SPI_send_tx_h.SPIConfig.SPI_DFF = SPI_DFF_8BITS;
	SPI_send_tx_h.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI_send_tx_h.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SPI_send_tx_h.SPIConfig.SPI_SSM = SPI_SSM_HWM;

	SPI_Init(&SPI_send_tx_h);
}

int main(void)
{
	char user_data[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tincidunt rhoncus urna ac nullam.";
	// This function is used to initialize the GPIO pins to behave as SPI2 pins
	SPI2_GPIOInits();

	GPIO_ButtonInit();

	// This function is used to initialize the SPI2 peripheral parameters
	SPI2_Init();

	/*
	 * Making SSOE 1 does NSS output enable.
	 * The NSS pin is automatically managed by the hardware.
	 * i.e when SPE = 1, NSS will be pulled to LOW
	 * when SPE = 0, NSS will be pull HIGH.
	 */
	SPI_SSOEConfig(SPI2, ENABLE);

	while (1)
	{
		while (!GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0))
			;

		delay();
		// Enable the SPI2 peripheral
		SPI_PeriControl(SPI2, ENABLE);

		uint16_t data_len = strlen(user_data);

		uint16_t data_len_msb = (data_len >> 8) & 0xFF;

		uint16_t data_len_lsb = data_len & 0xFF;

		SPI_SendData(SPI2, &data_len_msb, 1);

		SPI_SendData(SPI2, &data_len_lsb, 1);

		SPI_SendData(SPI2, (uint8_t*) user_data, strlen(user_data));

		while (SPI_GetFlagStatus(SPI2, SPI_BUSY_FLAG))
			;

		// Disable the SPI2 peripheral after transmitting
		SPI_PeriControl(SPI2, DISABLE);

	}
}
