/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void)
{
	for (int i = 0; i < 300000; i++)
		;
}

int main(void)
{
	SPI_Handler_t SPI_send_tx_h;
	SPI_send_tx_h.pSPIx = SPI2;
	SPI_send_tx_h.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SPI_send_tx_h.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FULL_DUPLEX;
	SPI_send_tx_h.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV2;
	SPI_send_tx_h.SPIConfig.SPI_DFF = SPI_DFF_8BITS;

	SPI_PeriClockControl(SPI2, ENABLE);
	SPI_Init(&SPI_send_tx_h);
}
